export const FILTER_REQUEST = "FILTER_REQUEST";
export const FILTER_SUCCESS = "FILTER_SUCCESS";
export const FILTER_FAILURE = "FILTER_FAILURE";
export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const GET_MORE_PRODUCTS = "GET_MORE_PRODUCTS";
export const GET_MORE_SUCCESS = "GET_MORE_SUCCESS";
export const FILTER_DATA = "FILTER_DATA";