export const GET_FIRST_PAGE_ADS_REQUEST = "GET_FIRST_PAGE_ADS_REQUEST";
export const GET_FIRST_PAGE_ADS_SUCCESS = "GET_FIRST_PAGE_ADS_SUCCESS";
export const GET_FIRST_PAGE_ADS_FAILURE = "GET_FIRST_PAGE_ADS_FAILURE";
export const RESET_FIRST_PAGE_ADS = "RESET_FIRST_PAGE_ADS";