export const GET_ALL_DATA_WITHOUT_TAG_REQUEST = "GET_ALL_DATA_WITHOUT_TAG_REQUEST";
export const GET_ALL_DATA_WITHOUT_TAG_SUCCESS = "GET_ALL_DATA_WITHOUT_TAG_SUCCESS";
export const GET_ALL_DATA_WITHOUT_TAG_FAILURE = "GET_ALL_DATA_WITHOUT_TAG_FAILURE";
export const RESET_PAGE = "RESET_PAGE";