export const GET_UPDATED_LOCATION_REQUEST = "GET_UPDATED_LOCATION_REQUEST";
export const GET_UPDATED_LOCATION_SUCCESS = "GET_UPDATED_LOCATION_SUCCESS";
export const GET_UPDATED_LOCATION_FAIL = "GET_UPDATED_LOCATION_FAIL";