export const GET_LOCATION_BY_ID_REQUEST = "GET_LOCATION_BY_ID_REQUEST";
export const GET_LOCATION_BY_ID_SUCCESS = "GET_LOCATION_BY_ID_SUCCESS";
export const GET_LOCATION_BY_ID_FAIL = "GET_LOCATION_BY_ID_FAIL";
export const GET_LOCATION_BY_ID_RESET = "GET_LOCATION_BY_ID_RESET";