export const FETCH_PRODUCTS_BY_TAGS_REQUEST = "FETCH_PRODUCTS_BY_TAGS_REQUEST";
export const FETCH_PRODUCTS_BY_TAGS_SUCCESS = "FETCH_PRODUCTS_BY_TAGS_SUCCESS";
export const FETCH_PRODUCTS_BY_TAGS_FAILURE = "FETCH_PRODUCTS_BY_TAGS_FAILURE";
export const RESET_PRODUCTS_BY_TAGS = "RESET_PRODUCTS_BY_TAGS";