export const GET_RANDOM_PRODUCT_REQUEST = "GET_RANDOM_PRODUCT_REQUEST";
export const GET_RANDOM_PRODUCT_SUCCESS = "GET_RANDOM_PRODUCT_SUCCESS";
export const GET_RANDOM_PRODUCT_FAILURE = "GET_RANDOM_PRODUCT_FAILURE";
export const RESET_RANDOM_PRODUCT = "RESET_RANDOM_PRODUCT";