export const SEARCH_ORDER_REQUEST = "SEARCH_ORDER_REQUEST";
export const SEARCH_ORDER_SUCCESS = "SEARCH_ORDER_SUCCESS";
export const SEARCH_ORDER_FAILURE = "SEARCH_ORDER_FAILURE";
export const RESET_SEARCH_ORDER = "RESET_SEARCH_ORDER";