export const GET_SELECTED_ITEM_REQUEST = "GET_SELECTED_ITEM_REQUEST";
export const GET_SELECTED_ITEM_SUCCESS = "GET_SELECTED_ITEM_SUCCESS";
export const GET_SELECTED_ITEM_FAILURE = "GET_SELECTED_ITEM_FAILURE";
export const RESET_SELECTED_ITEM = "RESET_SELECTED_ITEM";