export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FALUAERE = "UPDATE_PRODUCT_FAILURE";
export const GET_ALL_DATA_FOR_UPDATE_REQUEST = "GET_ALL_DATA_FOR_UPDATE_REQUEST";
export const GET_ALL_DATA_FOR_UPDATE_SUCCESS = "GET_ALL_DATA_FOR_UPDATE_SUCCESS";
export const GET_ALL_DATA_FOR_UPDATE_FAILURE = "GET_ALL_DATA_FOR_UPDATE_FAILURE";
export const RESET_PAGE_FOR_UPDATE = "RESET_PAGE_FOR_UPDATE";