export const GET_USERS_REQUEST_TYPE = "GET_USERS_REQUEST_TYPE";
export const GET_USERS_SUCCESS_TYPE = "GET_USERS_SUCCESS_TYPE";
export const GET_USERS_FAILURE_TYPE = "GET_USERS_FAILURE_TYPE";
export const RESET_USERS_TYPE = "RESET_USERS_TYPE";