export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FALUIERE = "GET_USER_ORDERS_FAILURE";
export const RESET_USER_ORDERS = "RESET_USER_ORDERS";